modLoader="javafml"
loaderVersion="[51,)"
license="CC BY-NC-SA 4.0"
issueTrackerURL="https://github.com/MattCzyr/ExplorersCompass/issues"
[[mods]]
    modId="explorerscompass"
    version="1.21-1.3.8-forge"
    displayName="Explorer's Compass"
    displayURL="https://github.com/MattCzyr/ExplorersCompass"
    authors="ChaosTheDude"
    description='''
    Search for and locate structures anywhere in the world.
    '''

[[dependencies.explorerscompass]]
    modId="forge"
    mandatory=true
    versionRange="[51,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.explorerscompass]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,)"
    ordering="NONE"
    side="BOTH"
