modLoader="javafml"
loaderVersion="${loader_version_range}"
license="CC BY-NC-SA 4.0"
issueTrackerURL="https://github.com/MattCzyr/ExplorersCompass/issues"
[[mods]]
    modId="explorerscompass"
    version="1.20.2-3.0.0-neoforge"
    displayName="Explorer's Compass"
    displayURL="https://github.com/MattCzyr/ExplorersCompass"
    authors="ChaosTheDude"
    description='''
    Search for and locate structures anywhere in the world.
    '''

[[dependencies.explorerscompass]]
    modId="neoforge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.explorerscompass]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
